name: Argus C1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm config set legacy-peer-deps true
        npm ci --no-audit --prefer-offline --ignore-scripts
      
    - name: Run basic verification
      run: |
        npm run lint || true
        NODE_OPTIONS=--max_old_space_size=4096 npm test -- --passWithNoTests
      env:
        CI: true
        NODE_ENV: test
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'release')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.version || '1.1.0' }}
        name: Release v${{ steps.get_version.outputs.version || '1.1.0' }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 